name: ALKUIP Dashboard Docker Quickstart

on:
  push:
    branches:
      - master

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
     
      - name: "Install Node/Yarn dependencies"
        run: |
          export NODE_OPTIONS="--max-old-space-size=8192"
          yarn install
          yarn build:tsc
          cp ./build/manifest.json ./dist/manifest.webapp

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: alkuidashboard
          path: |
            dist
            !dist/**/*.md
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/alkuip-dashboard:2.0.4
            ${{ secrets.DOCKERHUB_USERNAME }}/alkuip-dashboard:latest
      